### ISSUE TITLE
Issue with big precision of priority value

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-tile-editor#127]
@malx122 has issue when saving layout with big precision priority values like `0.900000001`, Starcounter fails to start database.

@malx122 could you please copy here the stack trace?

**Comment by malx122** [comment]
"System.FormatException: ScErrJsonValueWrongType (SCERR14004): The value does not correspond to the template property type. Property=""priority (Int64)"", Value=0.7675000000000001
Version: 2.1.1169.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR14004.
   at Starcounter.Advanced.XSON.JsonHelper.ThrowWrongValueTypeException(Exception innerException, String name, String type, String value) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.XSON\Serializer\Json\JsonHelper.cs:line 658
   at Starcounter.Advanced.XSON.JsonReader.ReadLong() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.XSON\Serializer\Json\JsonReader.cs:line 191
   at Starcounter.Advanced.XSON.StandardJsonSerializer.PopulateLong(Json json, Template template, JsonReader reader) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 775
   at Starcounter.Advanced.XSON.StandardJsonSerializer.PopulateObject(Json json, Template template, JsonReader reader) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 837
   at Starcounter.Advanced.XSON.StandardJsonSerializer.Populate(Json json, IntPtr source, Int32 sourceSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 887
   at Starcounter.Advanced.XSON.StandardJsonSerializer.PopulateArray(Json json, Template template, JsonReader reader) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 866
   at Starcounter.Advanced.XSON.StandardJsonSerializer.PopulateObject(Json json, Template template, JsonReader reader) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 837
   at Starcounter.Advanced.XSON.StandardJsonSerializer.Populate(Json json, IntPtr source, Int32 sourceSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 887
   at Starcounter.Json.PopulateFromJson(Byte[] source, Int32 sourceSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.XSON\Class Json\Json.Serializing.cs:line 131
   at Launcher.LauncherHelper.<Init>b__7(Request req) in c:\Projects\Github\Launcher\src\Launcher\Api\LauncherHelper.cs:line 82
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 559
HResult=-2146233033
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR14004
"

**Comment by malx122** [comment]
System.Exception: ScErrJsonPropertyNotFound (SCERR14003): The property is not defined in the template. Property="widthDynamic"
Version: 2.1.1169.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR14003.
   at Starcounter.Advanced.XSON.JsonHelper.ThrowPropertyNotFoundException(String name) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.XSON\Serializer\Json\JsonHelper.cs:line 672
   at Starcounter.Advanced.XSON.StandardJsonSerializer.PopulateObject(Json json, Template template, JsonReader reader) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 831
   at Starcounter.Advanced.XSON.StandardJsonSerializer.Populate(Json json, IntPtr source, Int32 sourceSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 887
   at Starcounter.Advanced.XSON.StandardJsonSerializer.PopulateArray(Json json, Template template, JsonReader reader) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 866
   at Starcounter.Advanced.XSON.StandardJsonSerializer.PopulateObject(Json json, Template template, JsonReader reader) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 837
   at Starcounter.Advanced.XSON.StandardJsonSerializer.Populate(Json json, IntPtr source, Int32 sourceSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 887
   at Starcounter.Advanced.XSON.StandardJsonSerializer.PopulateArray(Json json, Template template, JsonReader reader) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 866
   at Starcounter.Advanced.XSON.StandardJsonSerializer.PopulateObject(Json json, Template template, JsonReader reader) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 837
   at Starcounter.Advanced.XSON.StandardJsonSerializer.Populate(Json json, IntPtr source, Int32 sourceSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 887
   at Starcounter.Json.PopulateFromJson(Byte[] source, Int32 sourceSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.XSON\Class Json\Json.Serializing.cs:line 131
   at Launcher.LauncherHelper.<Init>b__7(Request req) in c:\Projects\Github\Launcher\src\Launcher\Api\LauncherHelper.cs:line 82
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 1114
   at Starcounter.Self.DoSelfCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.Internal\Rest\Self.cs:line 392
   at Starcounter.Self.GET[T](String uri, HandlerOptions ho) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.Internal\Rest\Self.cs:line 22
   at Launcher.LauncherHelper.<Init>b__b(Request req) in c:\Projects\Github\Launcher\src\Launcher\Api\LauncherHelper.cs:line 104
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-174\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 559
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR14003

**Comment by dan31** [comment]
CC @chrhol @miyconst can you pls move the issue to main Starcounter GH.

**Comment by chrhol** [comment]
I think this might not be a problem with big precision or missing property directly, but a problem with using json dynamically (or actually the parser that creates a template).

Basically if you have an array of items, each item MUST look the same for it to work, otherwise you get these kind of problems. Probably the first item in the array have a value that can be interpreted as an integer and later items is not.

See https://github.com/Starcounter/Starcounter/issues/3074 and https://github.com/Starcounter/Starcounter/issues/2571#issuecomment-77926751

Unfortunately I have forgotten these issues, I'm not sure how much work it will be to fix it. It's handled in the F# parser so maybe not supereasy.

**Comment by miyconst** [comment]
@dan31, @chrhol I have moved the issue about dynamic json arrays to the main repository, but still keep this one as we have to find a fix or workaround to make layout editor work even if the json not fixed.

Why we can't deliver setup as a string, not as a dynamic json? Personally I don't see any reason why would the setup be parsed on server side.

**Comment by chrhol** [comment]
> Why we can't deliver setup as a string, not as a dynamic json? Personally I don't see any reason why would the setup be parsed on server side.

I think the goal should be that it should work serverside and that we append the layouts as json-partials. That makes the solution more flexible to maintain and enhance.

However as a workaround it should be possible to not deserialize it on the server for the time being I guess. As far as I know it's only done in one place in `LauncherHelper.cs` today.

**Comment by miyconst** [comment]
@warpech what do you think?

**Comment by warpech** [comment]
I will try to switch Launcher to use Typed JSON for layouts and give feedback here.

**Comment by warpech** [comment]
I found two problems that don't make it easy to switch to Typed JSON:
1. Layout is actually stored as a string in the database, so it would still need to be parsed and converted on-the-fly
2. Layout may contain some arbitrary `juicy-tile-grid` extensions, of which Starcounter.Layout needs to be not aware
3. We actually don't use mutating view-model when layout changes. `juicy-tiles-setup-sync` uses REST API (POST) instead. It is commented in code as "temporary" but is likely to stay that way for long

For the above reasons, I will experiment with sending layout as string instead.

**Comment by warpech** [comment]
It seems that the problem will be fixed if we send `layout` as string.

It requires @chrhol to change:
- https://github.com/Starcounter/Starcounter/blob/develop/src/Starcounter.XSON/Serializer/Json/StandardJsonSerializer.cs#L297
- maybe also https://github.com/Starcounter/Starcounter/blob/fe4d59ad5024e0b6a52742f25cea3d22db2f658b/src/Starcounter.XSON/Serializer/Json/StandardJsonSerializer.cs#L626
- maybe anything else?

As well me to change https://github.com/StarcounterPrefabs/Launcher/blob/a10941ecf19c662db40734760103ad34e3cad906/src/Launcher/wwwroot/sys/starcounter-include/starcounter-include.html#L122 to:

``` js
    LauncherPartialPrototype.partialChanged = function(newVal){
      if(this.partial){
        var html = this.partial.Html;
        !html && console.warn("partial.Html for", this, "is missing.");
        !this.partial.PartialId && console.warn("partial.PartialId for", this, "is missing.");
        if(this.isAttached && html){
          this.sync.setAttribute("name", this.partial.PartialId);
          this.sync.storedValue = typeof this.partial.layout == "string" ? JSON.parse(this.partial.layout) : this.partial.layout;
          this.grid.setAttribute("name", this.partial.PartialId);
          if(this.partial.layout){
            this.grid.setup = typeof this.partial.layout == "string" ? JSON.parse(this.partial.layout) : JSON.parse(JSON.stringify(this.partial.layout));
          }
          this.partial.Html && this.template.setAttribute("content", this.partial.Html);
          this.template.model = this.partial;
        }
      }
    };
```

@tomalec, @miyconst any comments?

**Comment by miyconst** [comment]
No. I am fine with it.

**Comment by tomalec** [comment]
Well, we tried to make layout setups work as any other JSON property driven by Puppet. Last year we thought about implementing some layout related logic on server-side (versioning, branches/matrix matching, AI/robot phase etc.) I believe stringifying it would complicate this part as well.

Layouts were stored as string at the very beginning due to bugs, so it will probably work this time, so I'm fine, with making it work :)

But as Extremely Clean Solutions Departament, I have to say, that it would be nice to eat our own dog food, and be able to use Puppet flow at any point of JSON setup.

**Comment by warpech** [comment]
Decided then. Until we have a better support for https://github.com/Starcounter/Starcounter/issues/3074, we must go with JSON layout as a string.

It requires changes by me in Launcher (which I will do tonight) and by @chrhol in Starcounter.

**Comment by warpech** [comment]
Client side updated. My changes will be available in Launcher 3.1.1, which should be released tonight by @tomalec. 

Reassigning to @chrhol for the server side part.

**Comment by tomalec** [comment]
[Launcher@3.1.1](https://github.com/StarcounterPrefabs/Launcher/releases/tag/3.1.1) released

**Comment by chrhol** [comment]
Sorry for the delay. I got a nasty cold and was out for a few days.

I've changed the lines in the serializer now (not pushed yet though).

Also I think these lines in the Launcher-project needs to be changed to string as well, the original stacktrace points to this location at least. I will change that as well, but I guess a new release might be needed again.
https://github.com/StarcounterPrefabs/Launcher/blob/master/src/Launcher/ViewModels/LauncherPage.json#L31
https://github.com/StarcounterPrefabs/Launcher/blob/master/src/Launcher/Api/LauncherHelper.cs#L75-L84

**Comment by chrhol** [comment]
Pushed changes in serializer now. I couldn't push to Launcher though. It looks like I only have read-access. Can someone else do the needed changes there?

**Comment by chrhol** [comment]
> I couldn't push to Launcher though. It looks like I only have read-access. Can someone else do the needed changes there?

Or maybe just ignore me :) Tried again and it worked.

**Comment by warpech** [comment]
Thanks @chrhol! I hope you are fine now.

That's because I have just granted you the rights :)

**Comment by chrhol** [comment]
> That's because I have just granted you the rights :)

Ohh, hehe, I thought I did something strange the first time. Thanks!

**Comment by warpech** [comment]
Looking good now. 

Layouts are loaded and saved as strings without parsing, which means that the problem should be fixed. I will release a new version of Launcher now.
